### ISSUE TITLE
Sign in with github oauth authorisation fails

### ISSUE THREAD

**Issue by DevasenaInupakutika** [softwaresaved/fat#145]
Hi,

When I launch FAT at [http://127.0.0.1:8000/](http://127.0.0.1:8000/), I get the sign in page with Github but the oauth authorization fails and doesn't let me allow FAT app to be authorised. Not sure what could be the issue. I have been trying for the past couple of days but can't sign in.

I have an account on FAT but don't remember my credentials if not with Github.
Is there a way i can sign up for FAT account?

**Comment by rgaiacs** [comment]
Hi @DevasenaInupakutika, I add some documentation yesterday covering how to configure authentication with GitHub, see https://github.com/softwaresaved/fat#github-oauth. When you run FAT on your local machine you can't sign in with GitHub. 😢 This is due how the web is implemented and we can't solve the problem. 

> Not sure what could be the issue.

Mainly, GitHub can't contact your server back because your server is running on http://127.0.0.1:8000.

> I have been trying for the past couple of days but can't sign in.

Sorry for that. Please don't spend more than one day trying something. :-) Open an issue!

> Is there a way i can sign up for FAT account?

You can create a **local** super user account following https://github.com/softwaresaved/fat#super-user.

**Comment by DevasenaInupakutika** [comment]
Ok. Thank you very much for clarifying this. Ah, that's the way oauth works when running on local machine. 

And oh, so the super user we create is as login credentials. 

Sure! Thanks again and just looked at the updated documentation. 

Closing this issue now.
